name: Test & Build
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: ["1.18"]
    name: Go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Download dependencies
        run: go mod tidy
      - name: Run tests
        run: go test ./pkg/... -v

  build:
    strategy:
      matrix:
        go: ["1.18"]
    runs-on: ubuntu-latest
    name: Build
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: go build
